spring.application.name=discografia

spring.mongodb.uri=mongodb+srv://eravest1985_db_user:tOIeshFbspdggzS8@eva-u2-spring.har4dko.mongodb.net/?appName=eva-u2-spring

spring.mongodb.database=discografica-db